### ISSUE TITLE
TODO: move shell scripts in dreambbs_snap back and check

### ISSUE THREAD

**Issue by holishing** [ccns/dreambbs#36]
- [x] move shell scripts to repo (`master`)
- [x] check and revised
- [x] port to testing branch

**Comment by holishing** [comment]
- [ ] move shell scripts to repo (`master`)
- [ ] check and revised
- [ ] port to testing branch
